version: "3.9"
services:
    traefik-proxy:
        image: traefik:v2.9
        container_name: traefik
        restart: always
        ports:
            - "80:80"
            - "127.0.0.1:8080:8080"
            - "443:443"
        environment:
            - TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL=${TRAEFIK_CERTIFICATESRESOLVERS_LETSENCRYPT_ACME_EMAIL}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./certs/:/certificates
            - ./config/:/etc/traefik/
            - ./letsencrypt:/letsencrypt
        networks:
          - frontend
networks:
    frontend:
      driver: bridge